version: '3.8'

services:
  # MCP Issue Management Server with Audio Cast Support
  issue-mcp:
    build: .
    container_name: issue-mcp
    restart: unless-stopped
    volumes:
      # Mount database from host
      - ../dashboard-app/data:/app/dashboard-data:ro
      # Mount planning directory for audio cast file storage
      - ../../planning:/planning
      # Persistent data directory
      - issue-mcp-data:/app/data
    environment:
      # Database configuration
      ISSUE_DB_PATH: /app/dashboard-data/issues.db
      
      # TTS Service configuration
      TTS_SERVER_URL: http://wyoming-piper:10200/api/tts
      
      # Audio processing configuration
      MAX_TRANSCRIPT_LENGTH: 10000
      TTS_TIMEOUT_MS: 30000
      FFMPEG_TIMEOUT_MS: 60000
      AUDIO_DELAY_MS: 500
      
      # Strict dependency checking (fail fast if dependencies missing)
      STRICT_DEPS: "true"
      
      # MCP mode (silent stdout for MCP protocol)
      MCP_MODE: "true"
    networks:
      - mcp-network
    depends_on:
      - wyoming-piper

  # Wyoming Piper TTS Service
  wyoming-piper:
    image: rhasspy/wyoming-piper:latest
    container_name: wyoming-piper
    restart: unless-stopped
    ports:
      - "10200:10200"
    volumes:
      # Cache directory for TTS models
      - piper-data:/data
    command: --voice en_US-lessac-medium
    environment:
      # Piper configuration
      PIPER_UPDATE_VOICES: "true"
      PIPER_LENGTH_SCALE: "1.0"
      PIPER_NOISE_SCALE: "0.667"
      PIPER_NOISE_W: "0.333"
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:10200"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  mcp-network:
    driver: bridge

volumes:
  issue-mcp-data:
    driver: local
  piper-data:
    driver: local